import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "./Providers/StoreProvider";

export const metadata: Metadata = {
  title: "Real Estate Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
